LIBS += $(LIB)

OBJS := \
  $(DIR)abbr0s.o \
  $(DIR)abbr0a.o \
  $(DIR)abbr0h.o \
  $(DIR)born.o \
  $(DIR)born_Sfe6.o \
  $(DIR)SquaredME.o

$(LIB): $(LIB)($(OBJS))

$(LIB)($(OBJS)): F-squaredme.d $(DIR)vars.h

